# Generated by Django 5.2.4 on 2025-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorraines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
