# Generated by Django 5.2.4 on 2025-08-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorraines', '0007_auto_20250805_2156'),
    ]

    operations = [
    ]
