# Generated by Django 5.2.4 on 2025-08-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorraines', '0009_newslettersubscriber_orderitem_name_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
